### ISSUE TITLE
getPaymentState() must be of the type int, null returned

### ISSUE THREAD

**Issue by aptipl** [imdhemy/laravel-in-app-purchases#103]
**Describe the bug**
When i try to get subscription payment status which is already cancel. Google response with null value in paymentState filed. and when i try to get this status using getPaymentState() below error come.

"message": "Return value of Imdhemy\\GooglePlay\\Subscriptions\\SubscriptionPurchase::getPaymentState() must be of the type int, null returned",
    "exception": "TypeError",
    "file": "/Applications/XAMPP/xamppfiles/htdocs/countdown/vendor/imdhemy/google-play-billing/src/Subscriptions/SubscriptionPurchase.php",
    "line": 358,

And i found that in this file at line number 358 below function is created which will always return integer value from the response. So kindly remove int type in this function show this will work properly.

public function getPaymentState(): int
    {
        return $this->paymentState;
    }

My response from google is as below.

Imdhemy\GooglePlay\Subscriptions\SubscriptionPurchase {#314
  #kind: "androidpublisher#subscriptionPurchase"
  #startTimeMillis: "1640092136381"
  #expiryTimeMillis: "1640092438495"
  #autoResumeTimeMillis: null
  #autoRenewing: false
  #priceCurrencyCode: "INR"
  #priceAmountMicros: "380303870"
  #introductoryPriceInfo: null
  #countryCode: "IN"
  #developerPayload: ""
  #paymentState: null
  #cancelReason: 1
  #userCancellationTimeMillis: null
  #cancelSurveyResult: null
  #orderId: "GPA.3346-0710-1463-60066..0"
  #linkedPurchaseToken: null
  #purchaseType: 0
  #priceChange: null
  #emailAddress: null
  #givenName: null
  #profileId: null
  #acknowledgementState: 0
  #externalAccountId: null
  #promotionType: null
  #promotionCode: null
  #obfuscatedExternalAccountId: null
  #obfuscatedExternalProfileId: null
}

**Comment by imdhemy** [comment]
Starting from the v `1.x`, all attributes are optional.
