### ISSUE TITLE
How to associate Google play receipt with real-time notifications ?

### ISSUE THREAD

**Issue by jeanremy** [imdhemy/laravel-in-app-purchases#104]
**Describe the bug**
Hi,
This is not really a bug, more a question about the best way to handle payments. 

To handle server events and properly associate them with a user, I use receipt validation to create a subscription with the current user. Then, when receiving events, I can use the event `$subscription->getUniqueIdentifier()` to retrieve the subscription and update it. Therefore, events only update subscriptions, never create one.

The logic works wells with iOS. During the purchase flow, I first validate the receipt for both platforms. With iOS, I can use the `original_transaction_id` in the receipt payload to create a subscription on my backend and update it later with AppStore Events and the `$subscription->getUniqueIdentifier()` property received.
But with Google Play, the receipt payload only contains an `orderId` property, which is different from the `$subscription->getUniqueIdentifier()`. 
Si, this brings me to these questions:

- Is there a way to make a link between the receipt received and the events received later with Google Play ?
- Is there another way / flow for storing subscription and associate them with a user ?

Thanks for you help and for this package !

**Comment by jeanremy** [comment]
For the record, I manage to make a link between receipt and events using purchaseToken and linkedPurchaseToken.

**Comment by mario-neb** [comment]
@jeanremy can you please share how you managed it?
