### ISSUE TITLE
Unable to Install on Laravel 6.x

### ISSUE THREAD

**Issue by hilal-hipster** [imdhemy/laravel-in-app-purchases#11]
**Package doesn't install on laravel 6.x**
Try to install the package on Laravel Framework `6.18.11`

**To Reproduce**
1. On Laravel Framework `6.18.11` try to install using  `composer require imdhemy/laravel-purchases`
2. See the error below 

```Using version ^0.8.1 for imdhemy/laravel-purchases
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for nesbot/carbon (locked at 2.36.0) -> satisfiable by nesbot/carbon[2.36.0].
    - Installation request for imdhemy/laravel-purchases ^0.8.1 -> satisfiable by imdhemy/laravel-purchases[0.8.1].
    - Can only install one of: guzzlehttp/guzzle[7.2.0, 6.5.5].
    - Can only install one of: guzzlehttp/guzzle[7.2.0, 6.5.5].
    - Can only install one of: guzzlehttp/guzzle[7.2.0, 6.5.5].
    - imdhemy/appstore-iap 0.3.0 requires guzzlehttp/guzzle ^7.2 -> satisfiable by guzzlehttp/guzzle[7.2.0].
    - imdhemy/laravel-purchases 0.8.1 requires imdhemy/appstore-iap ^0.3 -> satisfiable by imdhemy/appstore-iap[0.3.0, 0.3.1].
    - Conclusion: don't install imdhemy/appstore-iap 0.3.1
    - Installation request for guzzlehttp/guzzle (locked at 6.5.5) -> satisfiable by guzzlehttp/guzzle[6.5.5].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by hilal-hipster** [comment]
@imdhemy Brother can you please help me out, Need to manage recursive subscriptions state.

**Comment by hilal-hipster** [comment]
@imdhemy, can you please help me out, Need to manage recursive subscriptions state.

**Comment by imdhemy** [comment]
Hello, @hilal-hipster!

Just installed the package on a fresh installation of Laravel `laravel/framework": "^6.20"`, it works as expected, then I downgraded the version to `6.18.11`, it works as expected as well.

It seems to me that the error is related to `guzzlehttp/guzzle`, would you mind showing me a snippet of your `composer.json` file, the **require section** only, please.

**Comment by hilal-hipster** [comment]
> laravel

@imdhemy below is the requested require section from composer.json

"require": {
        "php": "^7.2",
        "aws/aws-sdk-php-laravel": "^3.5",
        "caouecs/laravel-lang": "~5.0",
        "consoletvs/charts": "6.*",
        "doctrine/dbal": "^2.10",
        "dusterio/laravel-aws-worker": "^0.1.26",
        "felixkiss/uniquewith-validator": "^3.4",
        "fideloper/proxy": "^4.0",
        "intervention/image": "^2.5",
        "laracrafts/laravel-url-shortener": "^0.4.0",
        "laravel/framework": "^6.2",
        "laravel/helpers": "^1.2",
        "laravel/passport": "^8.4",
        "laravel/socialite": "^4.3",
        "laravel/tinker": "^2.0",
        "league/flysystem-aws-s3-v3": "^1.0",
        "marksitko/laravel-unsplash": "^1.0",
        "predis/predis": "^1.1",
        "propaganistas/laravel-phone": "^4.2",
        "realrashid/sweet-alert": "^3.1",
        "spatie/geocoder": "^3.8",
        "spatie/laravel-medialibrary": "^7.0.0",
        "spatie/laravel-permission": "^3.11",
        "thomaswelton/laravel-gravatar": "^1.2"
    },

**Comment by hilal-hipster** [comment]
@imdhemy 
Brother, never mind I have just upgraded my laravel version to **"Laravel Framework 6.20.6
"** and with this upgrade, package installs successfully.
Thanks for the prompt help.
Stay Blessed
