### ISSUE TITLE
Call to undefined method Imdhemy\\AppStore\\Receipts\\ReceiptResponse::getProductId()

### ISSUE THREAD

**Issue by xshiyun** [imdhemy/laravel-in-app-purchases#115]
Contracts/SubscriptionContract.php

`/**
     * @return mixed|SubscriptionPurchase|ReceiptResponse
     */
    public function getProviderRepresentation();`

Subscriptions/AppStoreSubscription.php
retern Imdhemy\AppStore\ValueObjects\ReceiptInfo
`
public function getProviderRepresentation()
    {
        return $this->receipt;
    }
`

**Comment by imdhemy** [comment]
Fixed in #117
