### ISSUE TITLE
Subscription verifyRenewable in a loop always sends back first receipt response

### ISSUE THREAD

**Issue by Brune04** [imdhemy/laravel-in-app-purchases#119]
I'm using a cron to check if there are any active subscriptions that have been cancelled and running into an issue. I've got all my active subscriptions in a loop and then calling `Subscription::appStore()->receiptData($receipt_data)->renewable()->verifyRenewable()` and it works on the first call, but every other call, it will only return the first subscription in the loops data.

**To Reproduce**
Here's the code that I currently have. InAppSubscriptions includes the order_id and transaction_receipt from ios subscriptions
```
        foreach($in_app_subscriptions as $value)
        {
            if($value->platform == 'ios'){
                $receiptResponse = Subscription::appStore()->receiptData($value->transaction_receipt)->renewable()->verifyRenewable();

                if(!empty($receiptResponse->getPendingRenewalInfo()[0])){
                    $auto_renew = $receiptResponse->getPendingRenewalInfo()[0]->isAutoRenewStatus();
                    if($auto_renew === false){
                        //they are canceling if it's false
                        if(!empty($receiptResponse->getLatestReceiptInfo()[0])){
                            $expire_date_string = $receiptResponse->getLatestReceiptInfo()[0]->getExpiresDate()->getCarbon()->toDateTimeString();

                            $value->ends_at = $expire_date_string;
                            if($expire_date_string <= date("Y-m-d H:i:s")){
                                $value->status = 'cancelled';
                            }
                            $value->save();
                        }else{
                            Log::info('InAppSubscription Error. Could not find latest receipt info '.$value->id);
                            break;
                        }
                    }
                }else{
                    Log::info('InAppSubscription Error. Could not find renewal info '.$value->id);
                    break;
                }
            }else{
                //TODO: add this in for google play subs
            }
        }
```
I have verified that everything in `$value` has the correct data, but the `$receiptResponse` is always the response from the first item in the loop. Am I doing something wrong here? Or does everyone else have this same problem?

**Expected behavior**
Each receiptResponse should correspond  to the correct subscription receipt that I'm sending it

**Comment by imdhemy** [comment]
@Brune04 

Using a cron to check the subscription status is an antipattern. Instead, it would be best if you depended on server notifications.

The `verifyRenewable()` responsibility is to send the request to the App Store and create a response object for you. 
As long as it does, so there is no bug here. ✋

**Comment by gabrielibis** [comment]
I have the same problem. verifyRenewable uses the first receipt instead the new one. There is any type of cache? I losted some notification because a problem in my server then now I have to check each subscription.

**Comment by Brune04** [comment]
@gabrielibis the only way I found was to do it one at a time which isn't really the greatest when you have a lot of subscriptions to check.

**Comment by gabrielibis** [comment]
I just found the solution. Laravel store a instance of Imdhemy\Purchases\Subscription . To solve I use:

```
 $subscrionFacadeCleared = new \Imdhemy\Purchases\Subscription();
 $subscrionFacadeCleared->googlePlay();
```
 
 Instead of 
 
` Subscription::googleplay();`
