### ISSUE TITLE
CVEs in Composer Dependencies

### ISSUE THREAD

**Issue by FrancisVillarbaBSDL** [imdhemy/laravel-in-app-purchases#129]
**Describe the bug**
CVEs in dependencies for this package

**To Reproduce**
1. Instal LIAP composer dependency
2. Perform static analysis on source code with tools such as Trivvy
3. See the error.

See screenshot for errors.

**Error Message Image**
<img width="1070" alt="Screen Shot 2022-08-25 at 10 31 40 am" src="https://user-images.githubusercontent.com/86995338/186560963-9041bd26-9ea4-44b9-905c-5833353d0fa7.png">

**Expected behavior**
No high severity CVEs in the package found.

**Comment by imdhemy** [comment]
Thanks, @FrancisVillarbaBSDL for submitting this issue.
