### ISSUE TITLE
No Event are being Listened When subscription states are changed

### ISSUE THREAD

**Issue by hilal-hipster** [imdhemy/laravel-in-app-purchases#13]
Following up with the example provided to handle subscription purchase events.
Created a new Listener for "SubscriptionRenewed" as Well as "SubscriptionCanceled" events.
But when the subscription renewed nothing happens nor got any logs.

**Code in my "AutoRenewSubscriptionPlayStore" Listener**
```php
class AutoRenewSubscriptionPlayStore
{    
    /**
     * Handle the event.
     *
     * @param  object  $event
     * @return void
     */
    public function handle(SubscriptionRenewed $event)
    {
        Log::info($event);
        $notification = $event->getServerNotification();
        $subscription = $notification->getSubscription();
        $uniqueIdentifier = $subscription->getUniqueIdentifier();
        $expirationTime = $subscription->getExpiryTime();
        $userId = User::findUserBySubscriptionId($uniqueIdentifier,'PlayStore');
        $user = User::find($userId);
        $subscription = UserSubscription::where('subscription_id',$uniqueIdentifier)->where('user_id',$userId)->first();
        $subscription->subscription_ends = $expirationTime;
        $subscription->save();
        $file = (isset($user->profile_picture)) ? $user->profile_picture : (($user->mediaImages->count() > 0) ? $user->profile_image : '');
        $image = generateS3FilePath($file);
        event(new SendPushNotification($user->id, trans('notification.subscription_updated'), array(trans('notification.subscription_updated'),'Subscription Updated',$image)));
    }
}
```
@imdhemy Help needed

**Comment by imdhemy** [comment]
Did you make all the following steps?
## Google Play
1. Configure RTDN. [Configure Real-time developer notifications](https://developer.android.com/google/play/billing/getting-ready#configure-rtdn)
2. Use the specified route for the RTDN, [more information here](https://github.com/imdhemy/laravel-in-app-purchases#i1-routing).
3. Add the listener to the config file `purchase.php`, [attach the created listener](https://github.com/imdhemy/laravel-in-app-purchases#configuration) to the proper event.

## App Store
1. Configure the App store [server notifications](https://developer.apple.com/documentation/appstoreservernotifications/enabling_app_store_server_notifications).
2. Use the specified route for the App store server notifications, [more information here](https://github.com/imdhemy/laravel-in-app-purchases#i1-routing).
3. Add the listener to the config file `purchase.php`, [attach the created listener](https://github.com/imdhemy/laravel-in-app-purchases#configuration) to the proper event.

## Summary
The config file `purchase.php`, contains two separate groups for different purchase events, be sure to attach the listener to the proper event for [google](https://github.com/imdhemy/laravel-in-app-purchases/blob/3cd1ab5a58b81e775df7c905e92a1696a3ca05cc/config/purchase.php#L39) or [apple](https://github.com/imdhemy/laravel-in-app-purchases/blob/3cd1ab5a58b81e775df7c905e92a1696a3ca05cc/config/purchase.php#L58) after setting up the server push notifications on the provider console.
