### ISSUE TITLE
Class Tests\Doubles\UrlGeneratorDouble does not exist

### ISSUE THREAD

**Issue by Fliw** [imdhemy/laravel-in-app-purchases#132]
**Describe the bug**
after composer install it get error target class not found

**To Reproduce**
1. run composer require imdhemy/laravel-purchases
2. get Class Tests\Doubles\UrlGeneratorDouble not exist
```
Target Class [Tests\Doubles\UrlGeneratorDouble] does not exist.
```

**Expected behavior**
It Works normally

**Additional context**
However, it's work perfectly on my local computer (windows), then after go into ubuntu server and install it, it goes error.

![image](https://user-images.githubusercontent.com/56640907/186948018-88d84456-738c-4f79-b36c-c85bba983bfe.png)

**Comment by imdhemy** [comment]
Thanks @Fliw, Which Laravel version?

**Comment by Fliw** [comment]
@imdhemy mine was 8

**Comment by Fliw** [comment]
although, i was fix this using older version of the package, the version 0.x was perfectly run on me without any code changing.

**Comment by imdhemy** [comment]
@Fliw Okay, I'll check it and publish a new release asap.

It would be better to use version 1.x`.
