### ISSUE TITLE
[1.x] environment variable does not exist

### ISSUE THREAD

**Issue by imdhemy** [imdhemy/laravel-in-app-purchases#140]
### Discussed in https://github.com/imdhemy/laravel-in-app-purchases/discussions/139

<div type='discussions-op-text'>

<sup>Originally posted by **henry-ht** September  9, 2022</sup>
just declaring the environment variable GOOGLE_APPLICATION_CREDENTIALS in the .env file is not enough for the Google Auth Library for PHP to use it because it is null, reading the documentation of the previous plugin the only way to declare that environment variable is with the following code:

`putenv('GOOGLE_APPLICATION_CREDENTIALS=/path/to/my/credentials.json');`

[https://github.com/googleapis/google-auth-library-php](url)

After adding this line of code in a middleware, the plugin was able to give an affirmative answer.

It is necessary to document this or create a function that adds this variable so that it is accessible by the Google Auth Library for PHP.</div>

**Comment by imdhemy** [comment]
Hey @mretcoyy 

I just published a fix addressing this issue. (#176 , #179 )

So, to fix it on your code:

**Update the LIAP package to the latest version** `1.3.3` or later.

```
composer require imdhemy/laravel-purchases -W 
```

**Update your configuration file** `/config/liap.php` by adding the following key:

https://github.com/imdhemy/laravel-in-app-purchases/blob/295e38abe7e5bc2ce3e9929e2579a7c8f22fda59/config/liap.php#L33-L43

**Comment by mretcoyy** [comment]
Hi Dhemy
I still get 1.3.2
[image: image.png]

**Comment by imdhemy** [comment]
@mretcoyy 

This is related to composer, what about :

```
composer require -W  --no-cache imdhemy/laravel-purchases
```

**Comment by mretcoyy** [comment]
Hi Dhemy

Its working now.
I'm on 1.3.2
I add this line even if I'm on 1.3.2 but it works. thank you!
google_application_credentials' => env('GOOGLE_APPLICATION_CREDENTIALS',
null),
