### ISSUE TITLE
[1.x] Support requesting a test notification

### ISSUE THREAD

**Issue by imdhemy** [imdhemy/laravel-in-app-purchases#142]
Support requesting a test notification.

**Comment by Brune04** [comment]
Any update on this? I'm having issues with setting up the callbacks and having this would be a big help in figuring out the issue.

**Comment by imdhemy** [comment]
I'm currently working on [another project](https://github.com/piscibus/siklid-api). I have no problem to pause working on it to implement this feature. So, you can expect this feature to be released this week Inshallah 🤞

**Comment by imdhemy** [comment]
Hey @Brune04 

Just [released](https://github.com/imdhemy/laravel-in-app-purchases/releases/tag/1.4.0) this feature. You can find more information about the usage in the PR itself. I will update the documentation asap.

https://github.com/imdhemy/laravel-in-app-purchases/pull/183
