### ISSUE TITLE
Event Listeners config error

### ISSUE THREAD

**Issue by flycan** [imdhemy/laravel-in-app-purchases#144]
Imdhemy\Purchases\ServiceProviders\EventServiceProvider.php

$this->listen = (array)config('purchase.eventListeners');

No such config named purchase, maybe you should change this line to "liap.eventListeners"

**Comment by imdhemy** [comment]
@flycan 
Yes, you are right. The `config/purchase.php` was removed in this version.

Could you please submit a PR?
