### ISSUE TITLE
[1.x] Imdhemy\Purchases\PurchaseServiceProvider Not found

### ISSUE THREAD

**Issue by msalmanali0683** [imdhemy/laravel-in-app-purchases#160]
### Liap version(s) affected

1.0

### Description

Imdhemy\Purchases\PurchaseServiceProvider is not found and no config file created after publishng provide when we add mannual in config\app.php Purchaseservice provide not found
![image](https://user-images.githubusercontent.com/45806776/196011855-093b9770-3189-448c-ae57-23c27a334b5c.png)

### How to reproduce

`Imdhemy\Purchases\PurchaseServiceProvider::class,`

**Comment by imdhemy** [comment]
The `Imdhemy\Purchases\PurchaseServiceProvider` from `v0.x `was replaced by `Imdhemy\Purchases\ServiceProviders\LiapServiceProvider` in `v1.x`. You can find an [upgrade guide](https://imdhemy.com/laravel-iap-docs/docs/upgrade) in the documentation.

To publish the [configuration](https://imdhemy.com/laravel-iap-docs/docs/get-started/installation#configuration), use the following command:

```
php artisan liap:config:publish
```
