### ISSUE TITLE
JWS Parsing error

### ISSUE THREAD

**Issue by Rydgel** [imdhemy/laravel-in-app-purchases#168]
### Liap version(s) affected

1.3.2

### Description

Hi, I was trying to test this library using the Sandbox from Apple.
I'm managing to get Apple pinging the right webhook URL but this is crashing.

```
 "exception": "Lcobucci\\JWT\\Encoding\\CannotDecodeContent",
    "file": "/app/icobackend/vendor/lcobucci/jwt/src/Encoding/CannotDecodeContent.php",
    "line": 14,
    "message": "Error while decoding from JSON",
    "subcode": "unknown_error",
    "trace": [
        {
            "class": "Lcobucci\\JWT\\Encoding\\CannotDecodeContent",
            "file": "/app/icobackend/vendor/lcobucci/jwt/src/Encoding/JoseEncoder.php",
            "function": "jsonIssues",
            "line": 41,
            "type": "::"
        },
        {
            "class": "Lcobucci\\JWT\\Encoding\\JoseEncoder",
            "file": "/app/icobackend/vendor/lcobucci/jwt/src/Token/Parser.php",
            "function": "jsonDecode",
            "line": 70,
            "type": "->"
        },
        {
            "class": "Lcobucci\\JWT\\Token\\Parser",
            "file": "/app/icobackend/vendor/lcobucci/jwt/src/Token/Parser.php",
            "function": "parseHeader",
            "line": 33,
            "type": "->"
        },
```

Example of a payload:

```json
{"signedPayload":".eyJub3RpZmljYXRpb25UeXBlIjoiRVhQSVJFRCIsInN1YnR5cGUiOiJWT0xVTlRBUlkiLCJub3RpZmljYXRpb25VVUlEIjoiYWQ2YjZjY2UtODVhMS00MTBjLWE4NmYtMzU4ODA2ZGY3Y2VkIiwiZGF0YSI6eyJidW5kbGVJZCI6ImNvbS5pY29ub3NxdWFyZS5wcm8iLCJidW5kbGVWZXJzaW9uIjoiMSIsImVudmlyb25tZW50IjoiU2FuZGJveCIsInNpZ25lZFRyYW5zYWN0aW9uSW5mbyI6ImV5SmhiR...
```

Seems like my sandbox payload has no headers for some reason, do you know why?
Or maybe the library should be able to handle this case as well?

### How to reproduce

Sent a JWS payload without headers in the Apple webhook.

**Comment by imdhemy** [comment]
This is strange. I think this is an issue related to App Store itself. As you can see in the [documentation](https://developer.apple.com/documentation/appstoreservernotifications/signedpayload), the `signedPayload` is a [JWS](https://datatracker.ietf.org/doc/html/rfc7515), which consists of three parts, separated by dots. 

The first part is the header, the second part is the payload, and the third part is the signature.

The header part is used to verify the signature. So if the header is missing, how can the signature be verified?

Could you please double-check the received payload? How many dots are there?
You can try to decode it on https://jwt.io/ and check what is going on...

I will follow up with you, just tell me if it requires publishing a fix.

**Comment by Rydgel** [comment]
There is 2 dots on my payload, when I use jwt.io it decodes fine, there is just an empty header, which I agree doesn't make sense to decrypt the rest.

<img width="550" alt="Capture d’écran 2022-10-28 à 18 05 45" src="https://user-images.githubusercontent.com/6583/198682756-e523c502-47b3-4e1d-a608-f211c8a33198.png">

I'll double check my App Store settings and let you know.

**Comment by imdhemy** [comment]
Hello @Rydgel 

Could you please update me on this issue? Do you need any help?

**Comment by Rydgel** [comment]
I'm coming back to you tomorrow, I need to check this with the iOS devs

**Comment by Rydgel** [comment]
Today the error is gone, and the payloads look much better.
So I think it was a one-time error from Apple or something.
Sorry for bothering.

**Comment by imdhemy** [comment]
Thanks for the update. Not at all, I'm always happy to help.
