### ISSUE TITLE
[1.x] Show App store test notification in logs

### ISSUE THREAD

**Issue by imdhemy** [imdhemy/laravel-in-app-purchases#193]
### Description

The release `1.4` introduced requesting a testing notification from the App store. So, it makes sense to show the test notification in logs the same way we do for Google.

**Comment by imdhemy** [comment]
Oh! It's already implemented 🫢

https://github.com/imdhemy/laravel-in-app-purchases/blob/00b572bb4ddaed237f096da6a030eeb08c044ee5/src/Handlers/AppStoreV2NotificationHandler.php#L40-L46

**Comment by vinaye42** [comment]
in my case,  test notification didn't work.
in access.log we received 
172.70.43.153 - - [15/May/2024:06:43:26 +0000] "POST /liap/notifications?signature=&provider=app-store HTTP/1.1" 200 4043 "-" "Apache-HttpClient/4.5.14 (Java/11.0.23)"

**Comment by imdhemy** [comment]
Hi @vinaye42 
Are the signed routes enabled?

https://github.com/imdhemy/laravel-in-app-purchases/blob/3c0031880dc0bbd39ec89eac61fc3d0f32580dec/config/liap.php#L19

If yes, try again after disabling it. Just to debug the source of the issue.

**Comment by vinaye42** [comment]
Hi @imdhemy,

We set  'signed' => false, but still not getting notification,
![liap](https://github.com/imdhemy/laravel-in-app-purchases/assets/93908879/063a0baf-affe-4d5e-a7df-aebefe6e0257)

here we didn't get that log,
access.log
 [20/May/2024:04:56:18 +0000] "POST /liap/notifications?signature=(signature)&provider=app-store HTTP/1.1" 200 4043 "-" "Apache-HttpClient/4.5.14 (Java/11.0.23)"

**Comment by imdhemy** [comment]
AppStore allows requesting a [test notification](https://developer.apple.com/documentation/appstoreserverapi/request_a_test_notification) to test if your server is receiving the notifications. 

You can do that using the following Liap Command:

```
php artisan liap:apple:test-notification
```

If you are using the sandbox you can use the `--sandbox` option

```
php artisan liap:apple:test-notification --sandbox
```

Did you try that?

**Comment by vinaye42** [comment]
Hi @imdhemy,
We tried both,
php artisan liap:apple:test-notification
php artisan liap:apple:test-notification --sandbox
 
 it return,
 `
Client error: `POST https://api.storekit-sandbox.itunes.apple.com/inApps/v1/notifications/test` resulted in a `401 Unauthorized` response:
Unauthenticated

Request ID: CFF7PF6TYWLCB4YHPUR4I7RZD4.0.0
 `
 Did I miss any step?

**Comment by imdhemy** [comment]
Did you set the following credentials?

https://github.com/imdhemy/laravel-in-app-purchases/blob/3c0031880dc0bbd39ec89eac61fc3d0f32580dec/config/liap.php#L99-L114

**Comment by vinaye42** [comment]
Hi @imdhemy,
Yes we have set above detail,
we set SuperSecretKey_ABC123.p8 in laravel project root directory, 
for appstore_private_key path,  should we set path from /var/www/html/dir/SuperSecretKey_ABC123.p8 ?

**Comment by vinaye42** [comment]
Hey @imdhemy,
we also checked those detail in logs,
we also check jwt token which generated for 1 hour.

**Comment by imdhemy** [comment]
What about checking if the JWT token has valid information and signature using something like https://jwt.io/ ?

I want to help, but it looks to me like this is a configuration/debug issue, isn't it?

**Comment by vinaye42** [comment]
hi @imdhemy,
Yes, we have checked token on https://jwt.io/,
Below is the response,
{
  "iss": (issuer id),
  "iat": 1716198701.869388,
  "exp": 1716202301.869393,
  "aud": "appstoreconnect-v1",
  "bid": (bundle id)
}

**Comment by vinaye42** [comment]
hi @imdhemy,
php artisan liap:apple:test-notification --sandbox
we get the response like below:
Test notification token: (token) 
But on Subscribed from App Store , we didn't get log in
[laravel-in-app-purchases/src/Handlers/AppStoreV2NotificationHandler.php](https://github.com/imdhemy/laravel-in-app-purchases/blob/00b572bb4ddaed237f096da6a030eeb08c044ee5/src/Handlers/AppStoreV2NotificationHandler.php#L40-L46)

Lines 40 to 46 in
and not in our BuySubscription listner handler.
