### ISSUE TITLE
[1.x] Missing Google Application Credentials on LiapServiceProvider

### ISSUE THREAD

**Issue by rodrigolopespt** [imdhemy/laravel-in-app-purchases#196]
### Liap version(s) affected

1.4

### Description

Missing Google Application Credentials on LiapServiceProvider.

This
`
if (! file_exists($googleCredentials)) {
                throw new RuntimeException("Google Application Credentials file not found at $googleCredentials");
            }`

Should be

`
if (! file_exists(base_path($googleCredentials))) {
                throw new RuntimeException("Google Application Credentials file not found at $googleCredentials");
            }`

### How to reproduce

I've just installed the package and publish the config. I'm running an in a container. Don't know if thats why i got this error trying to specify the path for the credentials file.

### Possible Solution

Just add base_path(), so we are looking from the base path of our app.

**Comment by imdhemy** [comment]
I'll check it and get back to you.

**Comment by imdhemy** [comment]
Hi @rodrigolopespt,

IMHO using the configured value gives more flexibility to the developer. 

With current implementation, you can use the `base_path` in your configuration file `config/liap.php` helper as follows:

```diff
- 'google_application_credentials' => env('GOOGLE_APPLICATION_CREDENTIALS', null),
+ 'google_application_credentials' => base_path('/path/to/google-credentials.json'),
```

You can use different values for different environments, with the `.env` variable `GOOGLE_APPLICATION_CREDENTIALS`.

Or even combine both:

```diff
- 'google_application_credentials' => env('GOOGLE_APPLICATION_CREDENTIALS', null),
+ 'google_application_credentials' => base_path(env('GOOGLE_APPLICATION_CREDENTIALS')),
```

Let me know what you think.

**Comment by rodrigolopespt** [comment]
Im good with that 🙂 i've just hitted this because Im running my APP inside a lando container which wraps the whole APP in a app folder. So initial its not clear for me why the path from env its found 😛 Anyway.. i agree with you that its more flexible that way..
