### ISSUE TITLE
The data in the receipt-data property was malformed or the service experienced a temporary issue. Try again.

### ISSUE THREAD

**Issue by nurhazbiy** [imdhemy/laravel-in-app-purchases#219]
### Liap version(s) affected

1.4.2

### Description

I get the following error when i tried to verify receipt created on sandbox environment. is there any way to set the package mode to sandbox? i can't find any in documentation mentioning this, or there is some configuration error? i did added the appstore_password in environment though...

here is my code 
```
try {
    $receiptResponse = IAPSubscription::appStore()
        ->receiptData($payload['verification_data'])
        ->verifyReceipt();


    // Get the receipt status
    $receiptStatus = $receiptResponse->getStatus();

    if ($receiptStatus->isValid()) {
        $latestReceiptInfo = $receiptStatus->getLatestReceiptInfo();
        // You can loop all of them or either get the first one (recently purchased).
        $receiptInfo = $latestReceiptInfo[0];

        $productId = $receiptInfo->getProductId();
        $transactionId = $receiptInfo->getTransactionId();
        $originalTransactionId = $receiptInfo->getOriginalTransactionId();
        $expiresDate = $receiptInfo->getExpiresDate();
        // And so on...
        $jsonResponse = response()->json([
            'result' => 'success',
            'data' => true,
        ], 200);
    }
    else {
        // The receipt is invalid
        $jsonResponse = response()->json([
            'result' => 'success',
            'data' => false,
        ], 200);
    }
} catch (GuzzleException $e) {
    $jsonResponse = response()->json([
        'result' => 'error',
        'data' => [
            'code' => $e->getCode(),
            'message' => $e->getMessage(),
            'trace' => $e->getTraceAsString()
        ],
    ], 200);
} catch (InvalidReceiptException $e) {
    $jsonResponse = response()->json([
        'result' => 'error',
        'data' => [
            'code' => $e->getCode(),
            'message' => $e->getMessage(),
            'trace' => $e->getTraceAsString()
        ],
    ], 200);
}
```

### How to reproduce

fresh laravel with APPSTORE_PASSWORD set in .env

**Comment by nurhazbiy** [comment]
nevermind, i solved already. I found it online that store kit (sandbox mode) give broken verification data, and my apps on my phone is sending that kind of data when i run it on debug mode. everything is working when i run it on release mode using beta tester account. that's really confuse me a lot though. on second hand i really hope there are some real verification data that can be used for example on test unit (either for verification or server notification) so we can make sure the problem is either pour server or the payload we sent.

**Comment by imdhemy** [comment]
Thank you for returning your findings to the community. I used the sandbox during the development but I didn't face this problem.
