### ISSUE TITLE
Security Issue (?)

### ISSUE THREAD

**Issue by michavie** [imdhemy/laravel-in-app-purchases#22]
Just from quickly scanning the source I noticed there seems to be no guard on the server notifications controller that prevents people from sending malicious requests if they are aware of the endpoint's URL.

I see this as an issue since the routes are not configurable as well which exposes developers to such attacks when they show interaction with this repo publicly while being known for their app.

Without being an expert on the IAP topic, can we use signatures or similar here?

--
What are your thoughts on this?

**Comment by imdhemy** [comment]
Hi, @michavie 

Firstly, thank you for all of your contributions, I impressed by your GitHub account and liked your last contribution to vapor-core. Keep it Man! 💪

Secondly, It seems to me you are right, but The routes are configurable, [check this section](https://github.com/imdhemy/laravel-in-app-purchases#i1-routing).

I suggest creating a middleware to perform a server-to-server authentication or any other suggested idea. I'm going to check the providers' documentation about this.

Your contributions are welcomed! It's an honor for me to receive a pull request from you.

**Comment by michavie** [comment]
Thanks for the kind words!

I may be using the package and will be available to improve this package with you in that case 👍
