### ISSUE TITLE
[1.x] Google Play RTDN notification doesn't work with http url

### ISSUE THREAD

**Issue by kasus** [imdhemy/laravel-in-app-purchases#257]
### Liap version(s) affected

1.6.1

### Description

Google cloud Pub/Sub requires an https URL as an endpoint for Push.
When website has APP_URL configured in http, signed url is generated with http as well, so when you change it to https, signature is not valid anymore.

### How to reproduce

1. Set APP_URL in .env with http:// protocol
2. Set liap config option `routing.signed` to `true`
3. run `php artisan liap:url` and choose google play
4. Copy url and try to paste it as and Endpoint in Cloud pub/sub according to manual https://imdhemy.com/laravel-iap-docs/docs/server-notifications/google-play#create-a-pubsub-subscription

### Possible Solution

I guess signed url must be forced to be https.

**Comment by imdhemy** [comment]
Actually, this is how a signed URL should work. Any change in the generated URL should make it invalid, and it depends on the application key as well. So, the generated URL should be used as is in the same environment where it was generated.

This means, in production, you have `https` enabled already, So I don't think this is the issue.

Feel free to clarify if I am missing something.

**Comment by kasus** [comment]
Yeah, I mean it's definitely not a bug. I had app url set in http in .env because app is simply an api for mobile app so it never actually used it. But when generated url I got an issue, so I was thinking that forcing https on signed route could make onboarding for somebody a bit easier.

I think it could be resolved by updating this code
```
$this->urlGenerator->signedRoute('liap.serverNotifications');
```
with calling `forceScheme` on laravel's url generator

also, thanks for sharing great package

**Comment by imdhemy** [comment]
Got it. You have a point. I'd be happy to merge such a PR.

**Comment by imdhemy** [comment]
Hi @kasus

I created this draft PR #259  to fix this issue. But I found that forcing the `https` scheme will cause another issue in the development environment. All requests using the `http` scheme will fail to pass the signature verification method.

All solutions that come to my mind are depending on the configuration, which doesn't make any difference from the current situation. So I'm not sure if this PR is necessary. 

What do you think?

**Comment by imdhemy** [comment]
I'm closing this issue for now, please feel free to reopen it if required.
