### ISSUE TITLE
Value Object Time can not be constructed from null values

### ISSUE THREAD

**Issue by maulanayusupp** [imdhemy/laravel-in-app-purchases#29]
```ERROR:
Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Imdhemy\GooglePlay\ValueObjects\Time::__construct() must be of the type int, null given, called in /Applications/MAMP/htdocs/mobistar-backend/vendor/imdhemy/google-play-billing/src/Subscriptions/SubscriptionPurchase.php on line 303 in file /Applications/MAMP/htdocs/mobistar-backend/vendor/imdhemy/google-play-billing/src/ValueObjects/Time.php on line 21
Stack trace:
1. Symfony\Component\Debug\Exception\FatalThrowableError-&gt;() /Applications/MAMP/htdocs/mobistar-backend/vendor/imdhemy/google-play-billing/src/ValueObjects/Time.php:21
etc...

```
CODE:
```
try {
  if ($subscriptionPurchase->getAutoResumeTime() && $subscriptionPurchase->getAutoResumeTime() !== null) {
	  $autoResumeTimeMillis = $subscriptionPurchase->getAutoResumeTime()->getCarbon();
  }
  } catch (\Exception $e) {
  \Log::error('ReceiptHelper - verifyPlayerAndroid - autoResumeTimeMillis', [$e->getMessage()]);
  }
```
something weird on this getAutoResumeTime(), when I debug google has send null value for autoResumeTimeMillis, I have put some try catch and still error. anyone can help me?

Everything working well, the problem is because I need to check when the subscription paused with this key `autoResumeTimeMillis`

**Comment by maulanayusupp** [comment]
Hmmm when I try to changed manually in the vendor file, it works!
SubscriptionPurchase.php

From:
/**
   * @return Time
   */
  public function getAutoResumeTime(): Time
  {
      return new Time($this->autoResumeTimeMillis);
  }

To:

/**
   * @return Time
   */
  public function getAutoResumeTime(): Time
  {
      return new Time($this->autoResumeTimeMillis ?? 0);
  }

anyone can help me or update the package or maybe something wrong in my code?

Thanks

**Comment by imdhemy** [comment]
Hi @maulanayusupp,
Thank you for reporting this issue!

This issue is related to the [imdhemy/google-play-billing](https://github.com/imdhemy/google-play-billing) package, it's fixed in `v.0.3.4`. Run `composer update` to get the latest version.

**Comment by maulanayusupp** [comment]
Thank you!
