### ISSUE TITLE
Apple v2 server notification - unable to get is_trial_period

### ISSUE THREAD

**Issue by andykarpov** [imdhemy/laravel-in-app-purchases#291]
### Liap version(s) affected

1.7.0

### Description

Unable to get ```is_trial_period``` property from the apple server v2 notification.

### How to reproduce

In the previous version of library (for v1 type notifications) it was possible by doing this in the event listener:
```    public function handle(PurchaseEvent $event)
    {
            $notification = $event->getServerNotification();
            $subscription = $notification->getSubscription();
            $id = $subscription->getItemId();
            $uniqueIdentifier = $subscription->getUniqueIdentifier();
            $expirationTime = $subscription->getExpiryTime()->toDateTime();
            $receiptInfo = $subscription->getProviderRepresentation();
            $isTrial = isset($receiptInfo) && $receiptInfo->isTrialPeriod();
    }
```

In the current version ```$subscription->getProviderRepresentation()``` returns instance of ```V2DecodedPayload```, there is no such method.

**Comment by imdhemy** [comment]
The App store notifications v2 has a different payload than the v1. For v2, we receivea [signed payload](https://developer.apple.com/documentation/appstoreservernotifications/signedpayload) from apple.
Liap helps to verify and decode the received payload, and gives youthe [decoded payload](https://developer.apple.com/documentation/appstoreservernotifications/responsebodyv2decodedpayload).

So, I don't think this is a bug related to LIAP, and using V2 notifications requires some changes in your code.

---

**For checking the trial version, I'd recommend you the following:**

> **Warning**
> This is just a suggestion. You need to check if the [offerType](https://developer.apple.com/documentation/appstoreservernotifications/offertype) represents a trial in your case.

```php
$decodedPayload = $subscription->getProviderRepresentation();
$renewalInfo = $decodedPayload->getRenewalInfo();
$isTrial = $renewalInfo->getOfferType() === JwsRenewalInfo::OFFER_TYPE_INTRODUCTORY;
```

Feel free to reopen this issue if you have an alternative solution or if you think this is a bug in LIAP.

**Comment by andykarpov** [comment]
Thank you so much,  @imdhemy, I will try your solution. 
Anyway, I think it will be nice to reflect such case (and maybe other differences between v1 and v2) in the documentation.
