### ISSUE TITLE
Signed route returns "Unauthorized"

### ISSUE THREAD

**Issue by berkayakin** [imdhemy/laravel-in-app-purchases#355]
### Liap version(s) affected

1.8.1

### Description

Making a POST request to created signed route when `'signed' => true `in `liap.php`, it returns: `403 - This action is unauthorized.`

That's why Google can not deliver messages. They are unacked due to 403 responses. As soon as I disable `signed` option in config, all messages are delivered.

### How to reproduce

- Enable `'routing.signed'` option in `liap.php`.
- Create a signed route
- Make a POST request to created URL.

**Comment by imdhemy** [comment]
Hello, 
Did you provide Google with a [signed URL](https://imdhemy.com/laravel-iap-docs/docs/get-started/routing#generate-a-signed-url)? It should be generated on Production not local environment.

**Comment by berkayakin** [comment]
Hello @imdhemy,
Yes I provided Google with a signed URL I generated on the production.
I didn't make any changes to the URL. I just copied and pasted.

**Comment by imdhemy** [comment]
@berkayakin Umm, 
That requires debugging. 

Could you please, double check if Google appends any queries to the URL?

**Comment by berkayakin** [comment]
Sure, I will do it and share. But when I make a direct POST request to that signed URL, I also get "403 - Unauthorized". Is that expected?

**Comment by imdhemy** [comment]
I have no idea :) 
But you can try another [signed URL](https://laravel.com/docs/10.x/urls#signed-urls), and debug the problem there.
