### ISSUE TITLE
Validating receipts with the App Store verifyReceipt Deprecated

### ISSUE THREAD

**Issue by hemasharshar** [imdhemy/laravel-in-app-purchases#365]
### Liap version(s) affected

1.x

### Description

There is issue when verifyReceipt get error message : 
The data in the receipt-data property was malformed or the service experienced a temporary issue. Try again.

App Store Provider : Apple Store

### How to reproduce

verifyReceipt is Deprecated

**Comment by mecenas-1** [comment]
@imdhemy great job, I'm glad you share such works with the community! Thanks to such projects, learning and working become easier!

I noticed the same problem as above, any suggestions on how to solve it?

thank you!

**Comment by ajaymakwana888** [comment]
Hello @hemasharshar & @mecenas-1 

Have you found any solution to this problem? or Any alternate solution/suggestion, please?
