### ISSUE TITLE
Undefined array key "environment"

### ISSUE THREAD

**Issue by EtoileFilante** [imdhemy/laravel-in-app-purchases#37]
Hi there,

I have the latest version of this repo on latest laravel.

When Apple sends a Sandbox request to API and that the .env has the sandbox set to false, we get the following
```
Undefined array key "environment"
in vendor/imdhemy/appstore-iap/src/Receipts/ReceiptResponse.php:58 Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
```

Which should probably be more precise

**Comment by imdhemy** [comment]
Hi @EtoileFilante,

Add `dd($attributes)` in the line `in vendor/imdhemy/appstore-iap/src/Receipts/ReceiptResponse.php:58`, and check the response code.

I guess that there is an error status code, and here [the reference of status codes](https://developer.apple.com/documentation/appstorereceipts/status).

**Comment by EtoileFilante** [comment]
Yes you're right I do get the 21007 error which is appropriate. So it's really not a serious issue but it would be nice to have the error code description right from the library instead of a library error :)

**Comment by imdhemy** [comment]
@EtoileFilante,
>Yes you're right I do get the 21007 error which is appropriate. So it's really not a serious issue but it would be nice to have the error code description right from the library instead of a library error :)

This was a planned enhancement and is already implemented now.

>Also could you please document how to get the the_base64_encoded_receipt_data from an InitialBuy event listener?

Could you describe the use case?

**Comment by EtoileFilante** [comment]
Ok great thank you!

Nevermind for the the_base64_encoded_receipt_data, I thought that the verifyReceipt was the Apple equivalent of google's required subscription acknowledgment
