### ISSUE TITLE
Add support for multiple apps 

### ISSUE THREAD

**Issue by sabina1997** [imdhemy/laravel-in-app-purchases#379]
### Description

I have a case where 2 different apps are connected to a single backend, I need to handle events from both apps but in the lib configuration file I can put only one app credentials. Is there any way to do it with the current version or if not, are you thinking to have a new feature for this ?

**Comment by imdhemy** [comment]
It's already possible with the current version. I will document how to do it as soon as possible.

**Comment by robertnicjoo** [comment]
> It's already possible with the current version. I will document how to do it as soon as possible.

Any update on this?

**Comment by imdhemy** [comment]
Hi @robertnicjoo & @sabina1997 

You can always pass a `$client` instance to the Subscription & Product Facades. I believe you would not face problems with the App Store handling multiple apps as the App Store client does not depend on specific configurations related to an application, but the request requires the [Application password](https://imdhemy.com/laravel-iap-docs/docs/credentials/app-store) which you can pass to the facade as follows:

```php
 Subscription::appStore()->receiptData($receiptData)->password($password)->verifyReceipt();
```

The Google Play client requires a [JSON credentials file](https://imdhemy.com/laravel-iap-docs/docs/credentials/google-play) its path is usually stored in an environment value, to workaround this, you can pass the Google client to the Facades as follows:

```php
// you need to pass the json credentials decoded as an array
$client = \Imdhemy\GooglePlay\ClientFactory::createWithJsonKey($jsonKey);

// Then you can pass the client to the facade
Subscription::googlePlay($client)->packageName($appPackageName)->id($itemId)->token($token)->get();
```

Regarding the triggered events, you only need to add simple logic in your event handler to know from which app you received this notification.


> [!NOTE] 
> With this use case you need to store the application `google-app-credentials.json` in the DB. Make sure this data is encrypted in your database. The same for the App Store application password.

**Comment by robertnicjoo** [comment]
Maybe it's not a bad idea if you transfer Google client and App Store passwords to arrays instead of strings then simply use `in_array()` to see if incoming app info exists or not that way we don't need separate functions for each app.

_just an idea_

**Comment by alihassan143** [comment]
> Hi @robertnicjoo & @sabina1997
> 
> You can always pass a `$client` instance to the Subscription & Product Facades. I believe you would not face problems with the App Store handling multiple apps as the App Store client does not depend on specific configurations related to an application, but the request requires the [Application password](https://imdhemy.com/laravel-iap-docs/docs/credentials/app-store) which you can pass to the facade as follows:
> 
> ```
>  Subscription::appStore()->receiptData($receiptData)->password($password)->verifyReceipt();
> ```
> 
> The Google Play client requires a [JSON credentials file](https://imdhemy.com/laravel-iap-docs/docs/credentials/google-play) its path is usually stored in an environment value, to workaround this, you can pass the Google client to the Facades as follows:
> 
> ```
> // you need to pass the json credentials decoded as an array
> $client = \Imdhemy\GooglePlay\ClientFactory::createWithJsonKey($jsonKey);
> 
> // Then you can pass the client to the facade
> Subscription::googlePlay($client)->packageName($appPackageName)->id($itemId)->token($token)->get();
> ```
> 
> Regarding the triggered events, you only need to add simple logic in your event handler to know from which app you received this notification.
> 
> Note
> 
> With this use case you need to store the application `google-app-credentials.json` in the DB. Make sure this data is encrypted in your database. The same for the App Store application password.

@imdhemy how it will detect to read which json file any sample code ?

**Comment by alihassan143** [comment]
@imdhemy kindly provide code regarding event listener how it will detect that ?
