### ISSUE TITLE
Keeps Adding nested folder Paths probably in cache, and says google credentials not found in vendor/imdhemy/laravel-purchases/src/ServiceProviders/LiapServiceProvider.php:126

### ISSUE THREAD

**Issue by talhawish** [imdhemy/laravel-in-app-purchases#405]
### Liap version(s) affected

1.8

### Description

 Google Application Credentials file not found at /var/www/html/myweb/var/www/html/myweb/var/www/html/myweb/var/www/html/myweb/config/keys/myweb-399408-8e321e88de56.json
 
 even my google credentials were preset, due to this I was not even able to clear cache , now even if i have cleared cache and as i remove json file from deep path that is asked that file is not present , it satrts showing error and each time it keeps adding neted directory 

### How to reproduce

it has happened to me multiple times, this time I was installing redis php extension and suddenly my site was down, i was not even able to open anything, nor able to remove cache.

**Comment by imdhemy** [comment]
Hi @talhawish ,

Thank you for submitting this issue. I have removed the Run time exception which is thrown when the Google credentials file is not found.

You should either set the environment variable `GOOGLE_APPLICATION_CREDENTIALS` to a relative path from your base path or directly set the file path in the `config/liap.php` file.  
https://github.com/imdhemy/laravel-in-app-purchases/blob/3c0031880dc0bbd39ec89eac61fc3d0f32580dec/config/liap.php#L35-L45

However the thrown exception may block you from clearing the cache, but I believe LIAP is not responsible for the appended path problem. Could you please try the [latest published version](https://github.com/imdhemy/laravel-in-app-purchases/releases/tag/1.11.0)? Let me know if you face any issues.

**Comment by talhawish** [comment]
Thank you so much, I’ll try and let you know.

**Comment by imdhemy** [comment]
I am closing this issue. Feel free to re-open it if required.
