### ISSUE TITLE
Target class [Imdhemy\AppStore\Jws\Parser] does not exist.

### ISSUE THREAD

**Issue by omarsenusi** [imdhemy/laravel-in-app-purchases#426]
### Liap version(s) affected

1.3

### Description

When a notification is sent from the Apple Store regarding a subscription, a strange issue occurs

`<!--
Illuminate\Contracts\Container\BindingResolutionException: Target class [Imdhemy\AppStore\Jws\Parser] does not exist. in file /home/oatag/public_html/oatag/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 914
`

### How to reproduce

composer.json

`{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The skeleton application for the Laravel framework.",
    "keywords": ["laravel", "framework"],
    "license": "MIT",
    "require": {
        "php": "^8.1",
        "coderello/laravel-passport-social-grant": "^3.1",
        "diglactic/laravel-breadcrumbs": "^8.1",
        "guzzlehttp/guzzle": "^7.2",
        "imdhemy/laravel-purchases": "^1.3",
        "inertiajs/inertia-laravel": "^0.6.11",
        "jenssegers/agent": "^2.6",
        "kreait/firebase-php": "^7.10",
        "kreait/laravel-firebase": "^5.8",
        "laravel/framework": "^10.10",
        "laravel/passport": "^11.10",
        "laravel/sanctum": "^3.2",
        "laravel/socialite": "^5.11",
        "laravel/tinker": "^2.8",
        "laravel/ui": "^4.3",
        "robertboes/inertia-breadcrumbs": "^0.4.0",
        "rugaard/weatherkit": "^0.1.1",
        "socialiteproviders/apple": "^5.6",
        "spatie/image": "^3.4",
        "spatie/laravel-medialibrary": "11.0.0",
        "spatie/laravel-permission": "^6.7",
        "stevebauman/location": "^7.1",
        "thenextweb/passgenerator": "^0.5.0",
        "tightenco/ziggy": "^1.0",
        "twilio/sdk": "^7.16"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/breeze": "^1.27",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.18",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "phpunit/phpunit": "^10.1",
        "spatie/laravel-ignition": "^2.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "pestphp/pest-plugin": true,
            "php-http/discovery": true
        }
    },
    "minimum-stability": "stable",
    "prefer-stable": true
}
`
`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - lcobucci/jwt 5.2.0 requires ext-sodium * -> it is missing from your system. Install or enable PHP's sodium extension.
    - socialiteproviders/apple 5.6.1 requires lcobucci/jwt ^4.1.5 || ^5.0.0 -> satisfiable by lcobucci/jwt[5.2.0].
    - socialiteproviders/apple is locked to version 5.6.1 and an update of this package was not requested.

To enable extensions, verify that they are enabled in your .ini files:
    - F:\wamp64\bin\php\php8.2.18\php.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-sodium` to temporarily ignore these required extensions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require imdhemy/laravel-purchases:*" to figure out if any version is installable, or "composer require imdhemy/laravel-purchases:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
PS F:\projects\oatag> composer require imdhemy/laravel-purchases --ignore-platform-reqs
./composer.json has been updated
`

**Comment by imdhemy** [comment]
Hi @momar3632 
Your server is missing the `sodium` PHP extension. The composer error message is telling you that:
```
Problem 1
- lcobucci/jwt 5.2.0 requires ext-sodium * -> it is missing from your system. Install or enable PHP's sodium extension.
```

You need to add install and enable this extension first, and then run `composer install`.
