### ISSUE TITLE
Keep Getting Google Default Credentials Error

### ISSUE THREAD

**Issue by talhawish** [imdhemy/laravel-in-app-purchases#430]
### Liap version(s) affected

1.8

### Description

I keep getting this error even though  have set the variable in .env as well as I have set according to the google docs export GOOGLE_APPLICATION_CREDENTIALS="KEY_PATH".  but still I keep getting this error.

In my opinion it happens because when we cache the config file with php artisan optimize than .env variables are not used. so we have to also read from config file so what we can do in CredentialsLoader file is 

$path = getenv(self::ENV_VAR);

if(!$path && function_exists('config')){
   $path= config('liap.google_application_credentials');
}

this way it will also try to read from config file

Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc {"userId":1,"exception":"[object] (DomainException(code: 0): Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc at /var/www/html/vlinq/backend/vendor/google/auth/src/ApplicationDefaultCredentials.php:201)

### How to reproduce

Happens every time I try to make Subscription::googlePlay()->id($purchaseId)->token($purchaseToken)->get() request.

### Possible Solution

In my opinion it happens because when we cache the config file with php artisan optimize than .env variables are not used. so we have to also read from config file so what we can do in CredentialsLoader file is 

$path = getenv(self::ENV_VAR);

if(!$path && function_exists('config')){
   $path= config('liap.google_application_credentials');
}

this way it will also try to read from config file

**Comment by willbrowningme** [comment]
Same issue here, I managed to sort it by placing the JSON credentials file here:

```bash
~/.config/gcloud/application_default_credentials.json
```

As specified here - https://github.com/googleapis/google-auth-library-php/blob/main/src/CredentialsLoader.php#L97

**Comment by imdhemy** [comment]
@willbrowningme Thank you for your reply. 

I've removed the [Service provider workaround](https://github.com/imdhemy/laravel-in-app-purchases/pull/435) and updated the documentation.
