### ISSUE TITLE
Target class [App\Providers\PutSubscriptionOnHold] does not exist.

### ISSUE THREAD

**Issue by vishnu-b** [imdhemy/laravel-in-app-purchases#53]
**Describe the bug**
While all the other Google Subscription events are working without any issue, the PutSubscriptionOnHold event always keeps throwing Target class [App\Providers\PutSubscriptionOnHold] does not exist error.

**To Reproduce**
Fire a PutSubscriptionOnHold event from Google.

**Expected behavior**
The PutSubscriptionOnHold event should be handled like any other event.

**Comment by michavie** [comment]
two things come to mind:
- the package does not expose an event called `PutSubscriptionOnHold `, rather `SubscriptionOnHold`
- you seem to be missing an import for the event, or do you have your events stored in the `Providers` namespace

**Comment by vishnu-b** [comment]
@michavie Thank you so much for replying. It was a missing namespace issue on my end.
