### ISSUE TITLE
Subscription and ExpiryTime always null

### ISSUE THREAD

**Issue by Padi-dev-hoangdv** [imdhemy/laravel-in-app-purchases#54]
I followed the docs.
I got the uniqueIdentifier but I couldn't get the subscription and expiry time.
I logged it and it always return {}.

```php
<?php

namespace App\Listeners;

use App\Models\UserSubscriptionPlan;
use Carbon\Carbon;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Support\Facades\Log;
use Imdhemy\Purchases\Events\AppStore\DidChangeRenewalStatus;

class AppleDidChangeRenewalStatus
{
    /**
     * Create the event listener.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Handle the event.
     *
     * @param DidChangeRenewalStatus $event
     * @return void
     */
    public function handle(DidChangeRenewalStatus $event)
    {
        $notification = $event->getServerNotification();
        $subscription = $notification->getSubscription();
        $uniqueIdentifier = $subscription->getUniqueIdentifier();
        $expirationTime = $subscription->getExpiryTime();

        Log::debug("AppleDidChangeRenewalStatus");
        Log::debug(json_encode($subscription, true));
        Log::debug(json_encode($expirationTime, true));
        Log::debug($uniqueIdentifier);
    }
}

```

**Comment by michavie** [comment]
it looks like a misuse of the `Log` and `json_encode`:
- `Log::debug` accepts strings, use 2nd param $context for additional logging
- `json_encode` 2nd parameter isn't a boolean

you probably want to use other debugging methods that are more convenient and less error-prone - especially for these asynchronous scenarios - such as xDebug, Spatie's ray(), BeyondCode's expose, ...

**Comment by Padi-dev-hoangdv** [comment]
@michavie Thank you.
I got it after using Spatie's ray().
I also want to insert the subscription in my DB but it just insert {}.
How can I fix this.

The column's name ```data``` with type ```LONGTEXT```.
And I already have Array & JSON Casting in the model

```php
protected $casts = [
        'data' => 'array',
    ];
```

**Comment by imdhemy** [comment]
Hi, @Padi-dev-hoangdv!

It looks like a misuse. Neither the Subscription nor the Expiration time has a Jsonable or Arrayable representation, So if you want to save the Subscription in your DB, you have to create an array on your own and you can rely on the getter method of each class to create it.
