### ISSUE TITLE
How to get transactionId in Apple Store Subscription

### ISSUE THREAD

**Issue by Padi-dev-hoangdv** [imdhemy/laravel-in-app-purchases#57]
First of all. Thanks you for doing this great work. It save me a lot of time to deal with in app purchases.

```php
$notification = $event->getServerNotification();
$subscription = $notification->getSubscription();
$uniqueIdentifier = $subscription->getUniqueIdentifier();
```
I notice that we don't have any function to get transactionId in AppStoreSubscription.
How can I get it?

**Comment by imdhemy** [comment]
Hi, @Padi-dev-hoangdv

Thank you for submitting this issue and for the [PR](https://github.com/imdhemy/laravel-in-app-purchases/pull/58) as well!

You can get the transaction Id as follows:

```php
$notification = $event->getServerNotification();
$subscription = $notification->getSubscription();

/** @var ReceiptInfo $receiptInfo */
$receiptInfo = $subscription->getProviderRepresentation();
$transactionId = $receiptInfo->getTransactionId();
```
