### ISSUE TITLE
Method for receiving paymentState is missing

### ISSUE THREAD

**Issue by akl-zephyr** [imdhemy/laravel-in-app-purchases#59]
Hello. Good job!

Method for receiving paymentState is missing.

class: Imdhemy\GooglePlay\Subscriptions\SubscriptionPurchase;
property: $paymentState

Please add getPaymentState() method

**Comment by michavie** [comment]
consider submitting a PR

**Comment by imdhemy** [comment]
Hi @akl-zephyr,

This issue was fixed before submitting this issue. Excuse me for being late.
Feel free to check this discussion #56
