### ISSUE TITLE
How to a parse expiry time as carbon object?

### ISSUE THREAD

**Issue by skakrecha** [imdhemy/laravel-in-app-purchases#60]
i have a scenario where i want to check if the subscription has expired or not .
  $subscriptionReceipt = Subscription::googlePlay()->id($request->package_id)->token($request->purchase_id)->get();
     if($subscriptionReceipt){
         dd($subscriptionReceipt->getExpiryTime());
     }

now how do i check if the time has expired , because i am getting a TIME object .

thanks.

**Comment by venux92** [comment]
@skakrecha you can do `$subscriptionReceipt->getExpiryTime()->getCarbon()` 😉

**Comment by skakrecha** [comment]
> @skakrecha you can do `$subscriptionReceipt->getExpiryTime()->getCarbon()` 😉

ok thanks let me try

**Comment by imdhemy** [comment]
@skakrecha
Besides what @venux92 mentioned, you can use one of the following methods from the `Time` object:

```php
$subscriptionReceipt->getExpiryTime()->isPast(); // if true it is expired
$subscriptionReceipt->getExpiryTime()->isFutre(); // if false it is expired
```

Thank you all! 🙌🏻

**Comment by skakrecha** [comment]
Thanks a lot that was what I wanted !!
