### ISSUE TITLE
"Invalid Value" Response on Android

### ISSUE THREAD

**Issue by Iamscaredofcode** [imdhemy/laravel-in-app-purchases#68]
**Describe the bug**
When I try to acknowledge a production purchaseToken from Android, then I get this error from Google API
```
Client error: `GET https://androidpublisher.googleapis.com/androidpublisher/v3/applications/xxxxxxxx/purchases/subscriptions/xxxxxxx/tokens/veduehxdiekpzbeximftmfne.AO-J1OyKHFkcnNmxxxxxuGxjgkLhOnlSKBWNfL-xWALsKp_luGeOBNDcAFsJSmjqGarRUNTeIcJbpFUfoGaVMfAxxxxxxbkPfLFamwqICOgDHFeRUMFlxewqoVIDUnHpv` resulted in a `400 Bad Request` response:
{
  "error": {
    "code": 400,
    "message": "Invalid Value",
    "errors": [
      {
        "message": "Invalid Valu (truncated...)
```

**To Reproduce**
1. Get purchaseToken from mobile
2. Acknowledge it with this code:
```php
$subscription = Subscription::googlePlay()->id($sku)->token($purchaseToken);
$subscription->acknowledge();
```
3. See the error.

**Expected behavior**
I tested with Apple and it works on production, but it don't work with Android for some reason.

Do you have an idea? Is the code correct?

**Comment by imdhemy** [comment]
@Iamscaredofcode
I suggest you double-check your configuration related to Google Play. The purchase token may belong to another package name or another subscription ID.

**Comment by Iamscaredofcode** [comment]
I think this could been the problem... My colleague missed to update it in the frontend and it likely generated wrong purchaseToken... Thank you for the hint! I was looking in wrong place
