### ISSUE TITLE
Undefined index: original_application_version

### ISSUE THREAD

**Issue by Ripudamangithub** [imdhemy/laravel-in-app-purchases#69]
Hi @imdhemy , 

Getting this issue on production environment in iOS notifications event

Undefined index: original_application_version at ../imdhemy/appstore-iap/src/ValueObjects/Receipt.php:96

Thank you

**Comment by imdhemy** [comment]
Hi @Ripudamangithub !
Did you double-check the `'appstore_password' => env('APPSTORE_PASSWORD', ''),` configuration on production?

**Comment by Ripudamangithub** [comment]
Hi @imdhemy ,

thanks for quick response, yes I have checked the app specific password and used the same in my .env 

I have used other methods like verifyReceipt() and these are working fine for me but getting this issue on getting notifications for app store
