### ISSUE TITLE
Config publish error : mkdir() invalid path

### ISSUE THREAD

**Issue by EtoileFilante** [imdhemy/laravel-in-app-purchases#7]
Hello !

I just tried to install this package on a laravel 8 project, however I get mkdir(): Invalid path error when I try to publish the config using php artisan vendor:publish.

**Comment by imdhemy** [comment]
Kindly upgrade your composer.json file to use `"imdhemy/laravel-purchases": "^0.6.1"`.

**Comment by EtoileFilante** [comment]
Hey-

Thanks it solved it

**Comment by imdhemy** [comment]
You are welcome. As a side note, I'm enhancing this package periodically, try to use the latest published version, or use the `dev-master` release to get updates on the master branch.
