### ISSUE TITLE
status DID RENEW when I should receive INITIAL BUY

### ISSUE THREAD

**Issue by bishwadeep** [imdhemy/laravel-in-app-purchases#73]
**Describe the bug**
The bug is related to appstore. When I test the subscription, I receive the status DID RENEW when I should receive INITIAL BUY

**To Reproduce**
Purchase the subscription using sandbox user.
Check the server to server notification log

**Expected behavior**
I am expecting that AppstoreInitialBuyListener.php should receive the data when Initial buy happens.
**Full trace**
If applicable, add full error trace to the bug.

**Additional context**

**Comment by imdhemy** [comment]
Hi @bishwadeep , Thanks for reporting this.

Could you please provide a snapshot of the notification send by apple? You can do so using logs.

**Comment by bishwadeep** [comment]
Thank you for the prompt reply mate. I think the problem is in our side. The purchase may not be the initial one. That is why we are getting  the response in AppstoreDidChangeRenewal.php file
