### ISSUE TITLE
the Facades \ Subscription class   does not exist i am on laravel 5.8

### ISSUE THREAD

**Issue by henry-ht** [imdhemy/laravel-in-app-purchases#8]
**Describe the bug**
I install everything as the documentation dictates but a problem arises, that class does not exist on the facade.

**Comment by imdhemy** [comment]
I just released v.0.7.0, kindly upgrade your composer to use the [latest version](https://packagist.org/packages/imdhemy/laravel-purchases).
`imdhemy/laravel-purchases": "^0.7.0`

**Comment by henry-ht** [comment]
Method get return object empty...

**Comment by imdhemy** [comment]
@henry-ht 
Can you show a snippet of your code and the business logic you are trying to implement?

**Comment by GannuYadav** [comment]
Target class [Imdhemy\\Purchases\\Handlers\\JwsParser] does not exist.
