### ISSUE TITLE
facade return empty in \Imdhemy\Purchases\Facades\Subscription

### ISSUE THREAD

**Issue by henry-ht** [imdhemy/laravel-in-app-purchases#9]
**Describe the bug**
finish creating an order from the app and sending the data they return empty.

**Comment by imdhemy** [comment]
Hi, @henry-ht!

The subscriptions facade provides two main methods:
1. **Acknowledge:** If successful, the response body will be empty. [1]
2. **Get:** If successful, the response body contains a `SubscriptionPurchase` resource. [2]

This simulates the responses provided by Google in their developer API.

---
References:
* [1] [Method: purchases.subscriptions.acknowledge
](https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.subscriptions/acknowledge#response-body)

* [2] [Method: purchases.subscriptions.get
](https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.subscriptions/get#response-body)

**Comment by henry-ht** [comment]
Method get return object empty...

**Comment by imdhemy** [comment]
@henry-ht 
Can you show me a snippet of your code and the business logic you are trying to implement?

**Comment by henry-ht** [comment]
Before finding your library, implement google / apiclient with this it returns the results of the purchase in google play, I am passing the same data and the get method of that function returns me empty ...

I'm using the same code snippet that you put in your subscription shopping example that you use with the pakageName

`<?php
use Imdhemy\GooglePlay\Subscriptions\SubscriptionPurchase;
use Imdhemy\Purchases\Facades\Subscription;

Subscription::googlePlay()->packageName('com.example.name')->id($itemId)->token($token)->get();
`

**Comment by imdhemy** [comment]
Here is a dump and die from my test code:
```php
 $subscriptionPurchase = Subscription::googlePlay()
	->packageName('com.example.name')
	->id($this->itemId)
	->token($this->token)
	->get();

 dd($subscriptionPurchase);
```

```
  #kind: "androidpublisher#subscriptionPurchase"
  #startTimeMillis: "1604673254094"
  #expiryTimeMillis: "1604675472244"
  #autoResumeTimeMillis: null
  #autoRenewing: false
  #priceCurrencyCode: "EGP"
  #priceAmountMicros: "79990000"
  #introductoryPriceInfo: null
  #countryCode: "EG"
  #developerPayload: ""
  #paymentState: null
  #cancelReason: 1
  #userCancellationTimeMillis: null
  #cancelSurveyResult: null
  #orderId: "GPA.3304-9004-2706-84832..5"
  #linkedPurchaseToken: null
  #purchaseType: 0
  #priceChange: null
  #emailAddress: null
  #givenName: null
  #profileId: null
  #acknowledgementState: 1
  #externalAccountId: null
  #promotionType: null
  #promotionCode: null
  #obfuscatedExternalAccountId: null
  #obfuscatedExternalProfileId: null
```

I'm trying to do my best to help you, I need a snippet of your code (just a copy and paste), not my snippets.

**Comment by henry-ht** [comment]
How do I convert these results into an object or how can I access that data?

**Comment by henry-ht** [comment]
Excuse me, everything is solved

**Comment by imdhemy** [comment]
Okay, man!
There is a getter method for each key, as provided in the read me file.

For example:
```
$expiryTime = $subscription->getExpiryTime();
```
This provides an object of type `Time` which have the following methods:
1. `getCarbon()`: provides a Carbon instance.
2. `toDateTime()`: provides a DateTime instance.
3. `isFuture()`: checks if this time is in the future.
4. `isPast()`: checks if this is in the past.

check the following table:

| Method | Description |
| --- | --- |
| getKind | ... |
| isAutoRenewing | ... |
| getPriceCurrencyCode | ... |
| getPriceAmountMicros | ... |
| getCountryCode | ... |
| getDeveloperPayload | ... |
| getOrderId | ... |
| getLinkedPurchaseToken | ... |
| getEmailAddress | ... |
| getGivenName | ... |
| getProfileId | ... |
| getExternalAccountId | ... |
| getObfuscatedExternalAccountId | ... |
| getObfuscatedExternalProfileId | ... |
| getStartTime | ... |
| getExpiryTime | ... |
| getAutoResumeTime | ... |
| getIntroductoryPriceInfo | ... |
| getPriceChange | ... |
| getCancellation | ... |
| getPromotionType | ... |
| getAcknowledgementState | ... |

**Comment by imdhemy** [comment]
@henry-ht you are welcome ^^
