### ISSUE TITLE
The current user has insufficient permissions to perform the requested o (truncated...)

### ISSUE THREAD

**Issue by ChrAus** [imdhemy/laravel-in-app-purchases#94]
Hi there,

so I currently try to get this package working.
I created a service account and set up the json so it works.

As a result I get an error saying "The current user has insufficient permissions to perform the requested o (truncated...)".

I have granted the service user access to our app with which the payments are made.
I made a payment so I have a valid receipt_id and tried the following:

```
$itemId = 'paket_l';
$token = $receiptId;
Product::googlePlay()->id($itemId)->token($token)->get();
```

Any hints what might be causing this?

Thanks in advance

**Comment by ChrAus** [comment]
Was an issue with the API key

**Comment by p4u1d34n** [comment]
hey, can you tell me how you fixed the issue?, i have the same here, swapped the jwt out twice and still get it.. any help would be cool..

**Comment by ChrAus** [comment]
Hi, if I remember correctly the final issue was that I was caching the configuration in laravel.
If you cache the config  the env() function did not work anymore.

So first I made sure the API key was created exactly like it is mentioned in the docs and then I passed it on manually. There must be another issue here with some code, how I did it. Let me check.

**Comment by ChrAus** [comment]
I was referring to this one here:

https://github.com/imdhemy/laravel-in-app-purchases/issues/97

**Comment by p4u1d34n** [comment]
Hi thanks for this, i've tried to replicate things, but just keep hitting the same issue.

`
private function getGoogleAuthJson(){
    return cache()->rememberForever('google-auth-cache', function () {
        $keyStream = file_get_contents(resource_path() . '/certificates/google_access.json');
        return json_decode($keyStream, true);
    });
}

[...]
        $jsonKey = $this->getGoogleAuthJson();
        $scopes = [ClientFactory::SCOPE_ANDROID_PUBLISHER];
        $client = ClientFactory::createWithJsonKey($jsonKey, $scopes);
        $subscriptionReceipt = Subscription::googlePlay()->id($product)->token($token)->get();
[...]

`

this is such a head scratcher for me.. :(

**Comment by ChrAus** [comment]
So is jsonKey filled?

**Comment by p4u1d34n** [comment]
Yeah, it seems to be spot on.

**Comment by ChrAus** [comment]
Try to recreate the API key in that case.

**Comment by ChrAus** [comment]
Did it work?

**Comment by vesper8** [comment]
Just had the same problem I think. In the end it was necessary for my to make a small edit to my existing store products in order to speed up the propagation of the new certificate. We're so used to changes being near instant but it appears that with Google Play things take time sometimes. I found this issue on StackOverflow that brought this to light https://stackoverflow.com/questions/43536904/google-play-developer-api-the-current-user-has-insufficient-permissions-to-pe
